{% set name = "neotime" %}
{% set version = "1.7.0" %}
{% set sha256 = "e4655fba91c03d741fe830c9623cb6d3422bc5b568948911ed75a6b218ab2ef4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytz
    - six

test:
  imports:
    - neotime

about:
  home: http://neotime.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Nanosecond resolution temporal types
  description: |
    The neotime module defines classes for working with temporal data to 
    nanosecond precision.  These classes comprise a similar set to that 
    provided by the standard library datetime module.
  doc_url: http://neotime.readthedocs.io/en/latest/
  dev_url: https://github.com/technige/neotime 

extra:
  recipe-maintainers:
    - jjhelmus
