travis:
  secure:
    BINSTAR_TOKEN: PQ+N7I717BrKUDCW3gIUMAfkPaHFSevWUWqWsCCIigCpm8wSwpafWhL1PTWO68UObWd5v4Cm+RHIy7JmiJCi4iEKdrf/EmxlphHUQ1rlrL/to/diFnn8O2/PkIyrnPXccqQcpkM6yeAMTWdWlDfq7I8/jg+6uFAXbpD0pecSvW4FzMIF3aIv5iPbY18RzP4jP0xgOzgYbtHNYEbwwk+Ix695I5IsW3HuWoxaa0JOwNsNHFkg00SDc+qKZVvhkZJz41NQeATyd1S25RQYmt/oV1wowrrra48BkRNLNSFl1TaIrRsL9mPb1gF2yT6vXFWqG0IqTxtT/KUcgvIiTCwCe/06gmq1DkwIB2EZlZiYJWpqYooHn2Zxup9IEQMi6XOXwDYqxHPnI9tD+lBjqRBh5NWV4NpurtOTn9WgZA2008vg5zfkWsJvuz9Zdd9l+fQteopTVEFyhJw8+j377GpwVOTjSMBylC3b5F/vV5MHJPXGhsVnAEBnZ+bZMvipvWGZmttp9qKdpTsMK6xe/1pieNhsvSCmIsKILvCwy//omfyjGP/CQS8IAkP2xJ4y/1ADaCLjUSKMuAIKFadiZcKMujM+ghNmgMFoH25hDKSJnp9Kjqmvv4abD758wVJKQ1tLmlLmkXZh+sgcUBNzTo/ZUDc6wEguOa0YN48YdtekNGc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
